name: awsAuthentication
description: authenticating AWS
inputs: 
  aws_region: 
    description: "aws region."
    type: string
    required: true
  role-to-assume: 
    description: "role to assume"
    type: string
    required: true

runs:
  using: composite
  steps:

        uses: actions/checkout@v4
        
      - name: Setup AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws_region }}
