name: Run Tests

on:
  workflow_call:

jobs:
  test-bot-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate JSON Files
        run: |
          jq empty bot/bot-definition.json
          jq empty bot/intents/*.json
          jq empty bot/slots/*.json

      - name: Check Required Fields in JSON
        run: |
          if ! jq -e '.name and .roleArn' bot/bot-definition.json > /dev/null; then
            echo "Missing required fields in bot-definition.json"
            exit 1
          fi
