name: Setup Environment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
