name: Security Checks

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Run Linting
        run: |
          npm install eslint
          npx eslint bot/

      - name: SonarQube Analysis
        run: sonar-scanner -Dsonar.projectKey=lex-bot -Dsonar.sources=bot/

      - name: Dependency Review
        uses: actions/dependency-review-action@v3

      - name: Upload to JFrog
        run: |
          curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASSWORD }} -T bot/bot-definition.json "https://my.jfrog.io/artifactory/lex-bot/"
