name: Build & Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  id-token: write  # OIDC for AWS authentication

jobs:
  lint-and-test:
    name: Lint, Test & Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Linter
      run: pylint src/

    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: high

    - name: Run Tests
      run: pytest tests/
