name: Deploy Amazon Lex Bot

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string
      aws_region:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
      - name: Setup AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws_region }}
      - name: Deploy Lex Bot
        run: |
          aws lexv2-models create-bot --cli-input-json file://bot/bot-definition.json
          aws lexv2-models create-intent --cli-input-json file://bot/intents/Greetingintent.json
          aws lexv2-models create-intent --cli-input-json file://bot/intents/bookdoctorappointment.json
          aws lexv2-models create-slot-type --cli-input-json file://bot/slots/doctorcode.json