name: Deploy Amazon Lex Bot

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::438465155677:oidc-provider/token.actions.githubusercontent.com
          aws-region: us-east-1

      - name: Deploy Lex Bot
        run: |
          aws lexv2-models create-bot --cli-input-json file://bot/bot-definition.json
