name: Development Deployment

on: [push, pull_request]
    

jobs:

  trigger-deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      environment: dev
      aws_role_to_assume: arn:aws:iam::438465155677:oidc-provider/token.actions.githubusercontent.com
