name: Development Deployment

on: [push, pull_request]
    

jobs:

  trigger-deployment:
    permissions:
      id-token: write
      contents: read  
    uses: ./.github/workflows/deployment.yml
    with:
      aws_region: us-east-1
      environment: dev
     # role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
      role-to-assume: 
