name: Security & Compliance

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday
  pull_request:
    branches: [ main ]

permissions:
  security-events: write

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python  # Adjust based on project language

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
